server:
  port: 5051
spring:
  datasource:
    hikari:
      connectionTestQuery : SELECT 1
      username : root
      password: fdsa1234
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/db_route53?serverTimezone=UTC&characterEncoding=UTF-8
      #jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/db_test?serverTimezone=UTC&characterEncoding=UTF-8
  devtools:
    restart:
      enabled: true


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
#        format_sql: true

#    hibernate:
#      use-new-id-generator-mappings: false